defaults:
  - _self_
  - paths: example 
  # - model: Qwen3-30B-A3B-Instruct-2507
  # - model: DeepSeek-V3.2
  - model: Qwen3-235B-A22B-Instruct-2507

embedding_model_name: "BAAI/bge-large-en-v1.5"
# pathology: appendicitis
# pathology: cholecystitis
# pathology: diverticulitis
# pathology: pancreatitis 
pathologies: [appendicitis, cholecystitis, diverticulitis, pancreatitis]
agent: ZeroShot
prompt_template: VANILLA
summarize: True
fewshot: False
include_ref_range: False
bin_lab_results: False
bin_lab_results_abnormal: False
provide_diagnostic_criteria: False
include_tool_use_examples: False
abbreviated: True
self_consistency: False
only_abnormal_labs: False

seed: 2023
local_logging: True
run_descr:

first_patient:
patient_list_path:

order: pli
diagnostic_criteria:

rr_name: RR
diag_crit_writer_openai_api_key:
confirm_diagnosis: False
save_probabilities: False
pubmed_api_key: ""  # Set NCBI_API_KEY or pass --pubmed_api_key at runtime.
# use_pubmed: TRUE
use_pubmed: True
use_exp: True
use_guidelines: True

test_num: 400
# last_patho: pancreatitis
# last_patho: diverticulitis
last_patho: None
